background #FDFCFD
foreground #70748A

cursor #99A0C0
cursor_text_color background

selection_background #D7C1FC
selection_foreground #70748A

active_border_color #99A0C0
inactive_border_color #EAEAF0

window_padding_width 10
background_opacity 0.95

font_family Maple Mono Bold Italic
font_size 12

# ANSI

color0  #EAEAF0
color1  #FA9096
color2  #B7DDB8
color3  #F6D9C0
color4  #95B8FE
color5  #D7C1FC
color6  #BDFCEF
color7  #70748A

# Bright

color8  #D6D6DF
color9  #FFADB2
color10 #D8F3D8
color11 #FFE6B8
color12 #B7D1FF
color13 #E7D6FF
color14 #D4FFF6
color15 #8B8FA3

confirm_os_window_close 0

font_size 12

window_padding_width 10

background_opacity 0.95

